samples_dir: "$workdir/data"
r1_suffix: "_1.fq"
r2_suffix: "_2.fq"

outdir: "results"

# ----------------------------
# Conda activate 
# ----------------------------
envs:
  metawrap: "$workdir/miniconda3/bin/activate metawrap-env"
  drep: "$workdir/miniconda3/bin/activate drep"
  gtdbtk: "$workdir/miniconda3/bin/activate gtdbtk_r207"
  humann3: "$workdir/miniconda3/bin/activate humann3"
  phylophlan: "$workdir/miniconda3/bin/activate phylophlan"
  microbeannotator: "$workdir/miniconda3/bin/activate microbeannotator"
  
databases:
  gtdbtk: "$workdir/db/gtdb_r207v2/gtdb_r207/release207_v2"
  microbeannotator: "$workdir/db/MicrobeAnnotator_DB"
  metaphlan: "$workdir/db/metaphlan4"
  metaphlan_index: "mpa_vJun23_CHOCOPhlAnSGB_202403"

phylophlan:
  config: "$workdir/supermatrix_aa.cfg"
  db: "$workdir/Phylogeny/phylophlan_databases"

threads:
  qc: 8
  assembly: 40
  binning: 32
  refinement: 32
  drep: 60
  gtdbtk: 48
  prokka: 8
  microbeannotator: 12
  humann: 32
  phylophlan: 40


mem_mb: 100000


skip_bmtagger: true
